- name: Reinstall Hostinger VPS with a new template
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Reinstall VPS
      hostinger.vps.hostinger_vps_reinstall:
        token: "{{ hostinger_token }}"
        virtual_machine_id: "{{ vm_id }}"
        template_id: "{{ template_id }}"
        password: "{{ password }}"
        public_ssh_key_id: "{{ ssh_key_id | default(omit) }}"
        post_install_script_id: "{{ script_id | default(omit) }}"
